let g:netrw_liststyle = 3

let mapleader = " "
set nocompatible

set viminfofile=NONE
set backupdir-=.
set backupdir^=~/.config/vim/tmp

set number
set relativenumber

set cursorline
syntax on
set ttyfast " fast terminal for smoother redrawing
set termguicolors
colorscheme catppuccin_mocha

" Enable type file detection. Vim will be able to try to detect the type of file in use.
filetype on

" Whitespace
set wrap
set textwidth=120
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Searching
" set hlsearch
set incsearch
set ignorecase
set smartcase
set showmatch

" Cursor motion
set scrolloff=1
set backspace=indent,eol,start

" Set Mouse support
set mouse=a

" Better navigation: when no count is given, use gj/gk for j/k
" Obsidian compatible
nnoremap j gj
nnoremap k gk

" This is for visual mode, but didn't work in obsidian
xnoremap j gj
xnoremap k gk

" Set the commands to save in history default number is 20.
set history=100

" Status bar bottom - 0 = never, 1 = if 2 or more windows, 2 = always
set laststatus=2

set statusline=%f\ %y\ %m\ %r\ %=Line:\ %l\ Column:\ %c

" When in visual mode, you can move lines of text up and down
" Enter visual mode, select what you need to select and press J or K to move
" the section up or down
vmap J :m '>+1<CR>gv=gv
vmap K :m '<-2<CR>gv=gv 

" When going down or up, centers cursor in the middle of the screen
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz

" When searching and do n or N, cursor stays in the middle
nnoremap n nzzzv
nnoremap N Nzzzv

" Use gh to move to the beginning of the line in normal mode
" Use gl to move to the end of the line in normal mode
nnoremap gh ^
nnoremap gl $

" Set cursor to line in insert mode
let &t_SI = "\e[5 q"

" Set cursor to block in normal mode
let &t_EI = "\e[2 q"

" Q enters Ex mode, this disables it
nnoremap Q <nop>

" Open NetW
nnoremap <leader>e :Ex<CR>

set clipboard+=unnamedplus

xnoremap "+y y:call system("wl-copy", @")<cr>
nnoremap "+p :let @"=substitute(system("wl-paste --no-newline"), '<C-v><C-m>', '', 'g')<cr>p
nnoremap "*p :let @"=substitute(system("wl-paste --no-newline --primary"), '<C-v><C-m>', '', 'g')<cr>p

" show fold column, fold by markers
set foldcolumn=1
set foldmethod=marker

" indicate when a line is wrapped by prefixing wrapped line with '> '
set showbreak=......\ 

" always show tab line
set showtabline=2

" Smart way to move between windows
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

noremap <S-l> :bn<CR>
noremap <S-h> :bp<CR>
noremap <S-q> :bd<CR>
