# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [

    { on   = [ ".", "s" ], run  = "plugin what-size", desc = "Calc size of selection or cwd" },
    { on = [
        "c",
        "m",
    ], run = "plugin chmod", desc = "Chmod on selected files" },

    { on = "<A-1>", run = "plugin toggle-view --args=parent", desc = "Toggle parent" },
    { on = "<A-2>", run = "plugin toggle-view --args=current", desc = "Toggle current" },
    { on = "<A-3>", run = "plugin toggle-view --args=preview", desc = "Toggle preview" },

    { on = [
        "n",
        "f",
    ], run = "create", desc = "Create a new file" },
    { on = [
        "n",
        "d",
    ], run = "create --dir", desc = "Create a new directory" },

    { on = [
        "g",
        "a",
    ], run = "cd ~/.config/alacritty", desc = "Go to Alacritty" },
    { on = [
        "g",
        "b",
    ], run = "cd ~/Sync/backups", desc = "Go to Backups" },
    { on = [
        "g",
        "B",
    ], run = "cd ~/.local/bin", desc = "Go to Bin" },
    { on = [
        "g",
        "c",
    ], run = "cd ~/.config", desc = "Go to Configs" },
    { on = [
        "g",
        "d",
    ], run = "cd ~/.config/dunst", desc = "Go to Dunst" },
    { on = [
        "g",
        "D",
    ], run = "cd ~/Downloads", desc = "Go to Downloads" },
    { on = [
        "g",
        "e",
    ], run = "cd /etc", desc = "Go to Etc" },
    { on = [
        "g",
        "h",
    ], run = "cd ~/.config/hypr/configs", desc = "Go to Hyperland" },
    { on = [
        "g",
        "H",
    ], run = "cd ~", desc = "Go to Home" },
    { on = [
        "g",
        "k",
    ], run = "cd ~/.config/kitty", desc = "Go to Kitty" },
    { on = [
        "g",
        "l",
    ], run = "cd ~/.local", desc = "Go to Local" },
    { on = [
        "g",
        "n",
    ], run = "cd ~/.config/nvim", desc = "Go to Neovim" },
    { on = [
        "g",
        "N",
    ], run = "cd ~/Notes", desc = "Go to Notes" },
    { on = [
        "g",
        "P",
    ], run = "cd ~/Pictures", desc = "Go to Pictures" },
    { on = [
        "g",
        "r",
    ], run = "cd ~/.config/rofi", desc = "Go to Rofi" },
    { on = [
        "g",
        "R",
    ], run = "cd /", desc = "Go to Root" },
    { on = [
        "g",
        "S",
    ], run = "cd ~/Sync/", desc = "Go to Sync" },
    { on = [
        "g",
        "t",
    ], run = "cd ~/.config/tmux", desc = "Go to Tmux" },
    { on = [
        "g",
        "T",
    ], run = "cd ~/.local/share/Trash/files", desc = "Go to Trash" },
    { on = [
        "g",
        "v",
    ], run = "cd ~/.config/vim", desc = "Go to Vim" },
    { on = [
        "g",
        "w",
    ], run = "cd ~/.config/waybar", desc = "Go to Waybar" },
    { on = [
        "g",
        "y",
    ], run = "cd ~/.config/yazi", desc = "Go to Yazi" },
    { on = [
        "g",
        "z",
    ], run = "cd ~/.config/zsh", desc = "Go to Zsh" },
    { on = [
        "g",
        "Z",
    ], run = "cd ~/.config/zellij", desc = "Go to Zellij" },
    { on = [
        "g",
        "<Space>",
    ], run = "cd --interactive", desc = "Go to a directory interactively" },
    { on = [
        ".",
        "s",
    ], run = "plugin what-size", desc = "Calc size of selection or cwd" },
]
