[env]
TERM = "xterm-256color"

[window]
title = "Alacritty"
decorations_theme_variant = "none"
dynamic_title = true
dynamic_padding = true
blur = true
opacity = 1.0

# [window.dimensions]
# columns = 100
# lines = 25

[window.padding]
x = 0
y = 0

[bell]
animation = "EaseOutExpo"
duration = 0

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
blink_interval = 500
blink_timeout = 5

[cursor.style]
blinking = "Never"
shape = "Beam"

[font]
size = 14

[font.normal]
family = "JetbrainsMono Nerd Font"
style = "Regular"

[font.italic]
family = "JetbrainsMono Nerd Font"
style = "Italic"

[font.bold]
family = "JetbrainsMono Nerd Font"
style = "Bold"

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[general]
live_config_reload = true

# Themes --
import = [
  # "~/.config/alacritty/afterglow.toml",
  # "~/.config/alacritty/catppuccin_macchiato.toml",
  "~/.config/alacritty/catppuccin_mocha.toml",
  # "~/.config/alacritty/everforest_dark.toml",
  # "~/.config/alacritty/gruvbox_dark.toml",
  # "~/.config/alacritty/nordic.toml",
  # "~/.config/alacritty/tokyo-night.toml",
  "~/.config/alacritty/keybinds.toml",
]
